### ISSUE TITLE
RuntimeError: Unable to open /Users/hulk/Documents/InKe/scripts/align/shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by zwq11** [TalkUHulk/realworld-stylegan2-encoder#4]
Hello, I am having the following problem with the torch framework. Can you provide this predictor please?
![image](https://user-images.githubusercontent.com/49020748/183282790-c6745d78-17ea-4f3f-9bd3-716cfb6b5dcb.png)

**Comment by TalkUHulk** [comment]
> Hello, I am having the following problem with the torch framework. Can you provide this predictor please? ![image](https://user-images.githubusercontent.com/49020748/183282790-c6745d78-17ea-4f3f-9bd3-716cfb6b5dcb.png)

http://dlib.net/files/

**Comment by zwq11** [comment]
Thank you very, very much！

**Comment by hamza-projectz** [comment]
Download it from : [https://raw.githubusercontent.com/italojs/facial-landmarks-recognition/master/shape_predictor_68_face_landmarks.dat](url)

**Comment by hamza-projectz** [comment]
download it from [https://github.com/italojs/facial-landmarks-recognition/blob/master/shape_predictor_68_face_landmarks.dat]([facial-landmarks-recognition](facial-landmarks-recognition)
